env:
  es6: true
  node: true

plugins:
  - prettier

rules:

  # -- Prettier Rules ----------------------------------------------------------
  prettier/prettier:
    - error
    - singleQuote: true
